name: cake_aide_basic
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+25

environment:
  sdk: ^3.6.0
dependencies:
  file_picker: '>=8.1.2'
  crypto: ^3.0.0
  flutter_launcher_icons: 0.14.4
  background_fetch: ^1.0.0
  url_launcher: ^6.0.0
  permission_handler: ^12.0.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^19.5.0
  uuid: ^4.0.0
  path: ^1.0.0
  shared_preferences: ^2.3.2
  image_picker: '>=1.1.2'
  sign_in_with_apple: '>=6.1.2'
  google_sign_in: '>=6.2.1'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  share_plus: any
  supabase_flutter: '>=1.10.0'
  firebase_core: ^4.2.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: '>=5.3.3'
  collection: ^1.18.0
  sentry_flutter: ^9.8.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/

# Launcher icon configuration for Codemagic step "Generate Launch Icon"
flutter_launcher_icons:
  image_path: assets/images/app_logo.jpg
  android: true
  ios: true
